### ISSUE TITLE
Generate p+gamma (one single virtual particle) from QRules

### ISSUE THREAD

**Issue by shenvitor** [ComPWA/gluex-nstar#5]

**Comment by redeboer** [comment]
Long-term, we need to adapt QRules so that it can handle an initial state with two particles (https://github.com/ComPWA/qrules/issues/29). For now though, you'll have to create a virtual particle that represents the state $p\gamma$. An example for $e^+e^-$ can be found here:
https://qrules.readthedocs.io/0.10.x/usage/particle/#adding-custom-particle-definitions-through-python

I'm not entirely sure what the quantum numbers of the virtual particle for $p\gamma$ would be. You can try out some combinations, like creating a `Particle` with `isonspin=None`. Be careful though that the combination of quantum numbers for the `Particle` complies with [Gell-Mann–Nishijima](https://en.wikipedia.org/wiki/Gell-Mann%E2%80%93Nishijima_formula).

**Comment by shenvitor** [comment]
For the record:

allowed reaction types: "strong", "EM", and "weak":
![Screenshot 2024-06-06 at 11 59 07](https://github.com/ComPWA/gluex-nstar/assets/17490173/015f4532-8023-4313-a769-f55b1b666bdc)
![Screenshot 2024-06-06 at 11 59 24](https://github.com/ComPWA/gluex-nstar/assets/17490173/3bdbbbaf-6a58-4b06-ab55-7a0d53260fba)
<img width="585" alt="Untitled1" src="https://github.com/ComPWA/gluex-nstar/assets/17490173/7f5828d0-6445-435f-a823-756db3e3ffdc">


allowed reaction types: "strong", "EM":
![Screenshot 2024-06-06 at 12 20 49](https://github.com/ComPWA/gluex-nstar/assets/17490173/0037ec33-820f-40c5-bbab-761206640f42)
![Screenshot 2024-06-06 at 12 20 54](https://github.com/ComPWA/gluex-nstar/assets/17490173/8065ff4e-7010-451f-a7f2-9bf9d525547b)
![Screenshot 2024-06-06 at 12 21 00](https://github.com/ComPWA/gluex-nstar/assets/17490173/2680b5d3-8564-461d-ad7a-15733b89a262)



allowed reaction types: "strong":
![Screenshot 2024-06-06 at 12 21 31](https://github.com/ComPWA/gluex-nstar/assets/17490173/c23ce54f-13af-4f1a-af83-8eacac72728f)

**Comment by redeboer** [comment]
Awesome 👌
